name: Create and publish a Docker images into ghcr.io

on:
  push:
    branches: ['main']

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          
      - name: V1 - Build and push Docker image webapp
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: webapp/src/v1
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/webapp:v1
          labels: ${{ steps.meta.outputs.labels }}

      - name: V2 - Build and push Docker image webapp
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with: 
          context: webapp/src/v2
          push: true 
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/webapp:v2
          labels: ${{ steps.meta.outputs.labels }}

      - name: Build and push Docker image helloworld
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with: 
          context: helloworld/src
          push: true 
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/helloworld:v1
          labels: ${{ steps.meta.outputs.labels }}

      - name: Build and push Docker image webapp v2
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc 
        with: 
          context: webapp/src/v2
          push: true 
          tags: ${{ steps.meta.outputs.tags }} 
          labels: ${{ steps.meta.outputs.labels }}
      
      - name: Build and push Docker image app01
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc 
        with: 
          context: app01
          push: true 
          tags: ${{ steps.meta.outputs.tags }} 
          labels: ${{ steps.meta.outputs.labels }}

      - name: Build and push Docker image app02
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc 
        with: 
          context: app02
          push: true 
          tags: ${{ steps.meta.outputs.tags }} 
          labels: ${{ steps.meta.outputs.labels }}
      - name: Build and push Docker image app03
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc 
        with: 
          context: app03
          push: true 
          tags: ${{ steps.meta.outputs.tags }} 
          labels: ${{ steps.meta.outputs.labels }}

